KayStrobach:
  Menu:
    Menus:
      Development:
        Configuration:
          TemplatePathAndFileName:
        Items:
          1023:
            label:      'Development'
            iconclass:  'glyphicon glyphicon-cog'
            section:    1
            #action: TextController
            #controller: TextController
            #package:
            #rolles:
            items:
              1230:
                label:       "Controller"
                package:     "KayStrobach.DevelopmentTools"
                controller:  "Controller"
                action:      "index"
                iconclass:   "glyphicon glyphicon-play"
              2240:
                label:       "Model"
                package:     "KayStrobach.DevelopmentTools"
                controller:  "Model"
                action:      "index"
                iconclass:   "glyphicon glyphicon-play"
              3240:
                label:       "ViewHelper"
                package:     "KayStrobach.DevelopmentTools"
                controller:  "ViewHelper"
                action:      "index"
                iconclass:   "glyphicon glyphicon-play"
              4240:
                label:       "Commands"
                package:     "KayStrobach.DevelopmentTools"
                controller:  "Command"
                action:      "index"
                iconclass:   "glyphicon glyphicon-play"

          1124:
            label:      'Documentation'
            iconclass:  'glyphicon glyphicon-book'
            section:    1
            items:
              2000:
                label:       "TYPO3 FLUID Docs"
                url:         "http://wiki.typo3.org/Fluid"
                iconclass:   "glyphicon glyphicon-book"
              2010:
                label:       "TYPO3 FLOW Quickstart"
                url:         "http://docs.typo3.org/flow/TYPO3FlowDocumentation/Quickstart/Index.html"
                iconclass:   "glyphicon glyphicon-book"
              2020:
                label:       "TYPO3 The Definitive Guide"
                url:         "http://docs.typo3.org/flow/TYPO3FlowDocumentation/TheDefinitiveGuide/Index.html"
                iconclass:   "glyphicon glyphicon-book"

#          1017:
#            label:      'Controllers'
#            iconclass:  'glyphicon glyphicon-cog'
#            section:    0
#            #aggregator: classname